import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    domains: [
      "cdn.cnn.com",
      "ichef.bbci.co.uk",
      "static01.nyt.com",
      "media.cnn.com",
      "assets.bwbx.io",
      "www.reuters.com",
      "m.wsj.net",
      "s.yimg.com",
      "images.macrumors.com",
      "platform.theverge.com",
      "images.nintendolife.com",
      "www.gamespot.com",
      "media.eventhubs.com",
      "media.wired.com",
      "static.dw.com",
      "i.insider.com",
      "static.politico.com",
      "image.cnbcfm.com",
      "cdn.mos.cms.futurecdn.net",
      "dims.apnews.com",
      "nbcsports.brightspotcdn.com",
      "media-cldnry.s-nbcnews.com",
      "img.buzzfeed.com",
      "covers.openlibrary.org",
      "sportshub.cbsistatic.com",
      "cff2.earth.com",
      "neurosciencenews.com",
      "scx2.b-cdn.net",
      "gymnastics-now.com",
      "img.mlbstatic.com",
      "www.usatoday.com",
      "www.masslive.com",
      "cnnespanol.cnn.com",
      "a4.espncdn.com",
      "a3.espncdn.com",
      "a1.espncdn.com",
      "a.espncdn.com",
      "a2.espncdn.com",
      "images.axios.com",
      "www.ccn.com",
      "i0.wp.com",
      "cdn.arstechnica.net",
      "www.gematsu.com",
      "platform.polygon.com",
      "images.purexbox.com",
      "images.seattletimes.com",
      "i.guim.co.uk",
      "i.dailymail.co.uk",
      "i2-prod.getsurrey.co.uk",
    ],
  },
};

export default nextConfig;
