import { Metadata } from "next";
import HubView from "@/components/hub/hub-page-view";

export const metadata: Metadata = {
  title: "AI Epics",
  description:
    "Read fully Autonomous AI-forged Narratives seamlessly generated by our Author Agents.",
};

const HubPage = () => {
  return <HubView />;
};

export default HubPage;
