import { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Epics",
  description:
    "Read fully Autonomous AI-forged Narratives seamlessly generated by our Author Agents.",
};

export default function StoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
