"use client";

import { useEffect, useState } from "react";
import { AIStory, StoryResponse } from "@/types";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import StoryViewer from "@/components/story/story-viewer";
import StoryLibrary from "@/components/story/story-library";
import { Lock } from "lucide-react";
import Typography from "@/components/ui/custom/typography";

export default function StoryPage() {
  const [story, setStory] = useState<AIStory | null | "unauthorized">(null);
  const [loading, setLoading] = useState(true);
  const [isReading, setIsReading] = useState(false);

  useEffect(() => {
    const fetchStory = async () => {
      try {
        const token = localStorage.getItem("jwt");
        const baseUrl =
          process.env.NEXT_PUBLIC_API_BASE_URL ||
          "https://readhub-backend.onrender.com/api";

        const headers: HeadersInit = {
          "Content-Type": "application/json",
        };

        if (token) {
          headers["Authorization"] = `Bearer ${token}`;
        }

        const res = await fetch(`${baseUrl}/story/myStory`, {
          headers,
          cache: "no-store",
        });

        if (!res.ok) {
          if (res.status === 401) {
            setStory("unauthorized");
          } else {
            setStory(null);
          }
        } else {
          const data: StoryResponse = await res.json();
          let currentStory = data.story;

          // If we got a story and it's not being initialized, fetch full content
          if (currentStory && !data.isInitializing) {
            const fullRes = await fetch(`${baseUrl}/story/${currentStory.id}`, {
              headers,
              cache: "no-store",
            });
            if (fullRes.ok) {
              const fullData = await fullRes.json();
              currentStory = fullData.story;
            }
          }

          setStory(currentStory);
        }
      } catch (error) {
        console.error("Error fetching story:", error);
        setStory(null);
      } finally {
        setLoading(false);
      }
    };

    fetchStory();
  }, []);

  return (
    <div className="container mx-auto pb-20">
      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[50vh] gap-4">
          <div className="relative">
            <div className="w-16 h-16 border-4 border-blue-600/20 border-t-blue-600 rounded-full animate-spin" />
            <Sparkles className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-6 h-6 text-blue-600 animate-pulse" />
          </div>
          <p className="text-muted-foreground animate-pulse font-medium">
            Our AI agent is retrieving your masterpiece...
          </p>
        </div>
      ) : story === "unauthorized" ? (
        <div className="flex flex-col items-center justify-center min-h-[60vh] px-4 text-center">
          <div className="bg-blue-50 dark:bg-blue-950/30 p-6 rounded-full mb-4 relative group">
            <div className="absolute inset-0 bg-blue-500/20 blur-2xl rounded-full transition-all opacity-0" />
            <Lock className="w-8 h-8 text-blue-600 dark:text-blue-400 relative z-10" />
          </div>
          <h1 className="text-2xl font-bold mb-3">Exclusive Content</h1>
          <p className="text-muted-foreground text-sm max-w-sm mb-6 leading-relaxed">
            Sign in to your ReadHub account to unlock your story module. Witness
            our advanced AI agent craft unique, imaginative narratives every
            single day!
          </p>
          <Button
            asChild
            className="rounded-full px-6 py-3 h-auto text-base font-bold shadow-lg transition-all hover:shadow-xl active:scale-95"
          >
            <Link href="/login">Login to Start Reading</Link>
          </Button>
        </div>
      ) : (
        <>
          {story && (
            <StoryViewer
              story={story}
              onStoryUpdate={(updated) => setStory(updated)}
              onReaderToggle={(reading) => setIsReading(reading)}
            />
          )}
          {!story && (
            <div className="flex flex-col items-center justify-center py-20 px-4 text-center">
              <Typography
                variant="h2"
                className="text-2xl font-bold text-muted-foreground mb-2"
              >
                No Active Story
              </Typography>
              <Typography
                variant="p"
                className="text-muted-foreground max-w-sm"
              >
                New story will be generated by our AI agent or in the meantime
                browse the library below.
              </Typography>
            </div>
          )}
        </>
      )}

      {!isReading && (
        <div className="max-w-7xl mx-auto px-4 sm:px-8 mt-20">
          <StoryLibrary />
        </div>
      )}
    </div>
  );
}
